const PROXY_URL = new URL('https://googlebot.workerify.workers.dev/');

const USER_AGENT_GOOGLE = 'Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible ; Googlebot/2.1 ; +http://www.google.com/bot.html)';
const USER_AGENT_BING = 'Chrome/80.0.3987.92 Mobile Safari/537.36 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)';

const ALL_SITES = {
	'Adweek': 'adweek.com',
	'Algemeen Dagblad': 'ad.nl',
	'\u00C1mbito': 'ambito.com',
	'American Banker': 'americanbanker.com',
	'Baltimore Sun': 'baltimoresun.com',
	'Barron\'s': 'barrons.com',
	'Bloomberg': 'bloomberg.com',
	'Bloomberg Quint (free articles only)': 'bloombergquint.com',
	'BN De Stem': 'bndestem.nl',
	'Boston Globe': 'bostonglobe.com',
	'Brabants Dagblad': 'bd.nl',
	'Brisbane Times': 'brisbanetimes.com.au',
	'Business Insider': 'businessinsider.com',
	'Caixin': 'caixinglobal.com',
	'Central Western Daily': 'centralwesterndaily.com.au',
	'Chemical & Engineering News': 'cen.acs.org',
	'Chicago Tribune': 'chicagotribune.com',
	'Corriere Della Sera': 'corriere.it',
	'Crain\'s Chicago Business': 'chicagobusiness.com',
	'Daily Press': 'dailypress.com',
	'De Gelderlander': 'gelderlander.nl',
	'De Groene Amsterdammer': 'groene.nl',
	'DeMorgen': 'demorgen.be',
	'Denver Post': 'denverpost.com',
	'De Speld': 'speld.nl',
	'De Stentor': 'destentor.nl',
	'De Tijd': 'tijd.be',
	'de Volkskrant': 'volkskrant.nl',
	'Diario Financiero': 'df.cl',
	'Domani': 'editorialedomani.it',
	'Dynamed Plus': 'dynamed.com',
	'Eindhovens Dagblad': 'ed.nl',
	'El Mercurio': 'elmercurio.com',
	'El Mundo': 'elmundo.es',
	'El Pais': 'elpais.com',
	'El Periodico': 'elperiodico.com',
	'Elu24': 'elu24.ee',
	'Encyclopedia Britannica': 'britannica.com',
	'Estadão': 'estadao.com.br',
	'Examiner': 'examiner.com.au',
	'Expansión': 'expansion.com',
	'Financial News': 'fnlondon.com',
	'Financial Post': 'financialpost.com',
	'Financial Times': 'ft.com',
	'First Things': 'firstthings.com',
	'Foreign Policy': 'foreignpolicy.com',
	'Fortune': 'fortune.com',
	'Genomeweb': 'genomeweb.com',
	'Glassdoor': 'glassdoor.com',
	'Globes': 'globes.co.il',
	'Grubstreet': 'grubstreet.com',
	'Haaretz English': 'haaretz.com',
	'Haaretz': 'haaretz.co.il',
	'Handelsblatt': 'handelsblatt.com',
	'Harper\'s Magazine': 'harpers.org',
	'Hartford Courant': 'courant.com',
	'Harvard Business Review': 'hbr.org',
	'Herald Sun': 'heraldsun.com.au',
	'Het Financieele Dagblad': 'fd.nl',
	'History Extra': 'historyextra.com',
	'Humo': 'humo.be',
	'Il Manifesto': 'ilmanifesto.it',
	'Inc.com': 'inc.com',
	'Interest NZ': 'interest.co.nz',
	'Investors Chronicle': 'investorschronicle.co.uk',
	'La Nacion': 'lanacion.com.ar',
	'La Repubblica': 'repubblica.it',
	'La Stampa': 'lastampa.it',
	'La Tercera': 'latercera.com',
	'La Voix du Nord': 'lavoixdunord.fr',
	'L\'Echo': 'lecho.be',
	'Le Devoir': 'ledevoir.com',
	'Le Parisien': 'leparisien.fr',
	'Les Echos': 'lesechos.fr',
	'Loeb Classical Library': 'loebclassics.com',
	'London Review of Books': 'lrb.co.uk',
	'Los Angeles Business Journal': 'labusinessjournal.com',
	'Los Angeles Times': 'latimes.com',
	'Medium': 'medium.com',
	'Medscape': 'medscape.com',
	'Mexico News Daily': 'mexiconewsdaily.com',
	'MIT Sloan Management Review': 'sloanreview.mit.edu',
	'MIT Technology Review': 'technologyreview.com',
	'Mountain View Voice': 'mv-voice.com',
	'National Geographic': 'nationalgeographic.com',
	'National Post': 'nationalpost.com',
	'Neue Zürcher Zeitung': 'nzz.ch',
	'New Statesman': 'newstatesman.com',
	'New York Daily News': 'nydailynews.com',
	'New York Magazine': 'nymag.com',
	'New Zealand Herald': 'nzherald.co.nz',
	'NRC': 'nrc.nl',
	'NT News': 'ntnews.com.au',
	'Orange County Register': 'ocregister.com',
	'Orlando Sentinel': 'orlandosentinel.com',
	'Palo Alto Online': 'paloaltoonline.com',
	'Parool': 'parool.nl',
	'Postimees': 'postimees.ee',
	'PZC': 'pzc.nl',
	'Quartz (free articles only)': 'qz.com',
	'Quora': 'quora.com',
	'Quotidiani Gelocal': 'gelocal.it',
	'Republic.ru': 'republic.ru',
	'Reuters': 'reuters.com',
	'San Diego Union Tribune': 'sandiegouniontribune.com',
	'San Francisco Chronicle': 'sfchronicle.com',
	'Scientific American': 'scientificamerican.com',
	'Seeking Alpha': 'seekingalpha.com',
	'Slate': 'slate.com',
	'SOFREP': 'sofrep.com',
	'Star Tribune': 'startribune.com',
	'Statista': 'statista.com',
	'Stuff': 'stuff.co.nz',
	"Süddeutsche Zeitung": "sueddeutsche.de",
	'SunSentinel': 'sun-sentinel.com',
	'Tech in Asia': 'techinasia.com',
	'Telegraaf': 'telegraaf.nl',
	'Time': 'time.com',
	'The Advertiser': 'adelaidenow.com.au',
	'The Advocate': 'theadvocate.com.au',
	'The Age': 'theage.com.au',
	'The American Interest': 'the-american-interest.com',
	'The Atlantic': 'theatlantic.com',
	'The Australian Financial Review': 'afr.com',
	'The Australian': 'theaustralian.com.au',
	'The Business Journals': 'bizjournals.com',
	'The Canberra Times': 'canberratimes.com.au',
	'The Courier': 'thecourier.com.au',
	'The Courier Mail': 'couriermail.com.au',
	'The Cut': 'thecut.com',
	'The Daily Telegraph': 'dailytelegraph.com.au',
	'The Diplomat': 'thediplomat.com',
	'The Economist': 'economist.com',
	'The Globe and Mail': 'theglobeandmail.com',
	'The Herald': 'theherald.com.au',
	'The Hindu': 'thehindu.com',
	'The Irish Times (free articles only)': 'irishtimes.com',
	'The Japan Times': 'japantimes.co.jp',
	'The Kansas City Star': 'kansascity.com',
	'TheMarker': 'themarker.com',
	'The Mercury News': 'mercurynews.com',
	'The Mercury Tasmania': 'themercury.com.au',
	'The Morning Call': 'mcall.com',
	'The Nation': 'thenation.com',
	'The National': 'thenational.scot',
	'The News-Gazette': 'news-gazette.com',
	'The New Yorker': 'newyorker.com',
	'The New York Times': 'nytimes.com',
	'The Philadelphia Inquirer': 'inquirer.com',
	'The Saturday Paper': 'thesaturdaypaper.com.au',
	'The Seattle Times': 'seattletimes.com',
	'The Spectator Australia': 'spectator.com.au',
	'The Spectator (U.K.)': 'spectator.co.uk',
	'The Spectator (U.S.)': 'spectator.us',
	'The Sydney Morning Herald': 'smh.com.au',
	'The Telegraph': 'telegraph.co.uk',
	'The Toronto Star': 'thestar.com',
	'The Wall Street Journal': 'wsj.com',
	'The Washington Post': 'washingtonpost.com',
	'The Wrap': 'thewrap.com',
	'Times Literary Supplement': 'the-tls.co.uk',
	'Towards Data Science': 'towardsdatascience.com',
	'Trouw': 'trouw.nl',
	'Tubantia': 'tubantia.nl',
	'Vanity Fair': 'vanityfair.com',
	'Vrij Nederland': 'vn.nl',
	'Vulture': 'vulture.com',
	'Winston-Salem Journal': 'journalnow.com',
	'Wired': 'wired.com',
	'World Politics Review': 'worldpoliticsreview.com',
	'Zeit Online': 'zeit.de',
};

const ALL_HOSTNAMES = Object.values(ALL_SITES);

const RESTRICTIONS = {
	'adweek.com': /^((?!\.adweek\.com\/(.+\/)?(amp|agencyspy|tvnewser|tvspy)\/).)*$/,
	'barrons.com': /.+\.barrons\.com\/(amp\/)?article(s)?\/.+/,
	'economist.com': /.+economist\.com\/.+\/\d{1,4}\/\d{1,2}\/\d{2}\/.+/,
	'seekingalpha.com': /.+seekingalpha\.com\/article\/.+/,
	'techinasia.com': /\.techinasia\.com\/.+/,
	'ft.com': /.+\.ft.com\/content\//
};

// Don't remove cookies before page load
const ALLOW_COOKIES = [
	'ad.nl',
	'bd.nl',
	'bndestem.nl',
	'brisbanetimes.com.au',
	'canberratimes.com.au',
	'cen.acs.org',
	'demorgen.be',
	'denverpost.com',
	'destentor.nl',
	'ed.nl',
	'examiner.com.au',
	'gelocal.it',
	'gelderlander.nl',
	'grubstreet.com',
	'harpers.org',
	'hbr.org',
	'humo.be',
	'lesechos.fr',
	'lrb.co.uk',
	'medium.com',
	'mercurynews.com',
	'newstatesman.com',
	'nrc.nl',
	'nymag.com',
	'ocregister.com',
	'parool.nl',
	'pzc.nl',
	'qz.com',
	'scientificamerican.com',
	'seattletimes.com',
	'seekingalpha.com',
	'sofrep.com',
	'spectator.co.uk',
	'speld.nl',
	'tubantia.nl',
	'techinasia.com',
	'telegraaf.nl',
	'the-american-interest.com',
	'theadvocate.com.au',
	'theage.com.au',
	'theatlantic.com',
	'theaustralian.com.au',
	'thecut.com',
	'thediplomat.com',
	'themercury.com.au',
	'towardsdatascience.com',
	'trouw.nl',
	'vn.nl',
	'volkskrant.nl',
	'vulture.com',
	'nzz.ch',
	'handelsblatt.com',
	'thehindu.com',
	'financialpost.com',
	'haaretz.co.il',
	'haaretz.com',
	'themarker.com',
	'sueddeutsche.de',
	'gelocal.it',
	'elmundo.es',
	'time.com',
	'zeit.de',
	'expansion.com',
	'dailytelegraph.com.au'
];

// Removes cookies after page load
const REMOVE_COOKIES = [
	'ad.nl',
	'bd.nl',
	'bloombergquint.com',
	'bndestem.nl',
	'brisbanetimes.com.au',
	'canberratimes.com.au',
	'cen.acs.org',
	'demorgen.be',
	'denverpost.com',
	'destentor.nl',
	'ed.nl',
	'examiner.com.au',
	'gelderlander.nl',
	'globes.co.il',
	'grubstreet.com',
	'harpers.org',
	'hbr.org',
	'humo.be',
	'lesechos.fr',
	'mercurynews.com',
	'newstatesman.com',
	'nrc.nl',
	'nymag.com',
	'ocregister.com',
	'pzc.nl',
	'qz.com',
	'scientificamerican.com',
	'seattletimes.com',
	'sofrep.com',
	'spectator.co.uk',
	'speld.nl',
	'telegraaf.nl',
	'theadvocate.com.au',
	'theage.com.au',
	'theatlantic.com',
	'thecut.com',
	'thediplomat.com',
	'towardsdatascience.com',
	'tubantia.nl',
	'vn.nl',
	'vulture.com',
	'wsj.com',
	'medium.com'
];

// select specific cookie(s) to hold from removeCookies domains
const REMOVE_COOKIES_EXCEPTIONS = {
	'qz.com': ['gdpr'],
	'wsj.com': ['wsjregion'],
	'seattletimes.com': ['st_newsletter_splash_seen']
};

// select only specific cookie(s) to drop from removeCookies domains
const REMOVE_COOKIES_WHITELIST = {
	'ad.nl': ['temptationTrackingId'],
	'ambito.com': ['TDNotesRead'],
	'bd.nl': ['temptationTrackingId'],
	'bndestem.nl': ['temptationTrackingId'],
	'demorgen.be': ['TID_ID'],
	'destentor.nl': ['temptationTrackingId'],
	'ed.nl': ['temptationTrackingId'],
	'fd.nl': ['socialread'],
	'gelderlander.nl': ['temptationTrackingId'],
	'humo.be': ['TID_ID'],
	'nrc.nl': ['counter'],
	'pzc.nl': ['temptationTrackingId'],
	'tubantia.nl': ['temptationTrackingId'],
	'speld.nl': ['speld-paywall']
};

// Override User-Agent with Googlebot
const USE_GOOGLEBOT_SITES = [
	'adelaidenow.com.au',
	'barrons.com',
	'couriermail.com.au',
	'fd.nl',
	'genomeweb.com',
	'heraldsun.com.au',
	'lavoixdunord.fr',
	'ntnews.com.au',
	'quora.com',
	'seekingalpha.com',
	'telegraph.co.uk',
	'theaustralian.com.au',
	'themercury.com.au',
	'thenational.scot',
	'wsj.com',
	'kansascity.com',
	'republic.ru',
	'nzz.ch',
	'handelsblatt.com',
	'df.cl',
	'ft.com',
	'wired.com',
	'zeit.de'
];

// Override User-Agent with Bingbot
const USE_BINGBOT_SITES = [
	'haaretz.co.il',
	'haaretz.com',
	'themarker.com'
];

const BLOCK_SCRIPTS = {
	'adweek.com': /.+\.lightboxcdn\.com\/.+/,
	'afr.com': /afr\.com\/assets\/vendorsReactRedux_client.+\.js/,
	'businessinsider.com': /(.+\.tinypass\.com\/.+|cdn\.onesignal\.com\/sdks\/.+\.js)/,
	'chicagotribune.com': /.+:\/\/.+\.tribdss\.com\//,
	'economist.com': /(.+\.tinypass\.com\/.+|economist\.com\/engassets\/_next\/static\/chunks\/framework.+\.js)/,
	'editorialedomani.it': /(js\.pelcro\.com\/.+|editorialedomani.it\/pelcro\.js)/,
	'foreignpolicy.com': /(cdn\.cxense\.com\/|\.tinypass\.com\/)/,
	'fortune.com': /.+\.tinypass\.com\/.+/,
	'haaretz.co.il': /haaretz\.co\.il\/htz\/js\/inter\.js/,
	'haaretz.com': /haaretz\.com\/hdc\/web\/js\/minified\/header-scripts-int.js.+/,
	'inquirer.com': /.+\.tinypass\.com\/.+/,
	'lastampa.it': /.+\.repstatic\.it\/minify\/sites\/lastampa\/.+\/config\.cache\.php\?name=social_js/,
	'lrb.co.uk': /.+\.tinypass\.com\/.+/,
	'medscape.com': /.+\.medscapestatic\.com\/.*medscape-library\.js/,
	'interest.co.nz': /(.+\.presspatron\.com.+|.+interest\.co\.nz.+pp-ablock-banner\.js)/,
	'repubblica.it': /scripts\.repubblica\.it\/pw\/pw\.js.+/,
	'spectator.co.uk': /.+\.tinypass\.com\/.+/,
	'spectator.com.au': /.+\.tinypass\.com\/.+/,
	'telegraph.co.uk': /.+telegraph\.co\.uk.+martech.+/,
	'thecourier.com.au': /.+cdn-au\.piano\.io\/api\/tinypass.+\.js/,
	'thenation.com': /thenation\.com\/.+\/paywall-script\.php/,
	'thenational.scot': /(.+\.tinypass\.com\/.+|.+thenational\.scot.+omniture\.js|.+thenational\.scot.+responsive-sync.+)/,
	'thewrap.com': /thewrap\.com\/.+\/wallkit\.js/,
	'wsj.com': /cdn\.ampproject\.org\/v\d\/amp-access-.+\.js/,
	'historyextra.com': /.+\.evolok\.net\/.+\/authorize\/.+/,
	'barrons.com': /cdn\.ampproject\.org\/v\d\/amp-access-.+\.js/,
	'irishtimes.com': /cdn\.ampproject\.org\/v\d\/amp-access-.+\.js/,
	'elmercurio.com': /(merreader\.emol\.cl\/assets\/js\/merPramV2.js|staticmer\.emol\.cl\/js\/inversiones\/PramModal.+\.js)/,
	'sloanreview.mit.edu': /(.+\.tinypass\.com\/.+|.+\.netdna-ssl\.com\/wp-content\/themes\/smr\/assets\/js\/libs\/welcome-ad\.js)/,
	'latercera.com': /.+\.cxense\.com\/+/,
	'lesechos.fr': /.+\.tinypass\.com\/.+/,
	'thehindu.com': /ajax\.cloudflare\.com\/cdn-cgi\/scripts\/.+\/cloudflare-static\/rocket-loader\.min\.js/,
	'technologyreview.com': /.+\.blueconic\.net\/.+/,
	'spectator.us': /(cdn\.cxense\.com\/.+|\.tinypass\.com\/.+)/,
	'gelocal.it': /(\.repstatic\.it\/minify\/sites\/gelocal\/.+\/config\.cache(_\d)?\.php|cdn\.ampproject\.org\/v\d\/amp-(access|ad)-.+\.js)/,
	'elmundo.es': /cdn\.ampproject\.org\/v\d\/amp-(access|ad|consent)-.+\.js/,
	'time.com': /\/time\.com\/dist\/meter-wall-client-js\..+\.js/,
	'thestar.com': /\.com\/api\/overlaydata/,
	'elpais.com': /(\.epimg\.net\/js\/.+\/(noticia|user)\.min\.js|\/elpais\.com\/arc\/subs\/p\.min\.js|cdn\.ampproject\.org\/v\d\/amp-(access|(sticky-)?ad|consent)-.+\.js)/,
	'expansion.com': /cdn\.ampproject\.org\/v\d\/amp-(access|ad|consent)-.+\.js/,
	'chicagobusiness.com': /(\.tinypass\.com\/|\.chicagobusiness\.com\/.+\/js\/js_.+\.js)/,
	'dailytelegraph.com.au': /cdn\.ampproject\.org\/v\d\/amp-(access|ad|consent)-.+\.js/,
	'theglobeandmail.com': /(\.theglobeandmail\.com\/pf\/dist\/engine\/react\.js|smartwall\.theglobeandmail\.com\/)/
};
